name: Multiline Shell Commands Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run multiline shell commands
        run: |
          echo "Hello"
          echo "This is"
          echo "a multiline"
          echo "shell command!"
